-- WorldTable one-worksheet installer.
-- Paste this entire file into a Snowsight worksheet and run it as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS WORLDTABLE;
CREATE SCHEMA IF NOT EXISTS WORLDTABLE.APP;

CREATE API INTEGRATION IF NOT EXISTS WORLDTABLE_GITHUB_API
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ('https://github.com/ezer-k/chat_to_table')
  ENABLED = TRUE;

CREATE GIT REPOSITORY IF NOT EXISTS WORLDTABLE.APP.SOURCE
  API_INTEGRATION = WORLDTABLE_GITHUB_API
  ORIGIN = 'https://github.com/ezer-k/chat_to_table.git';

ALTER GIT REPOSITORY WORLDTABLE.APP.SOURCE FETCH;

EXECUTE IMMEDIATE FROM
  @WORLDTABLE.APP.SOURCE/branches/main/sql/install.sql;
